[package]
name = "aoc2024day09"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-util = { path = "../../../util" }

derive_more.workspace = true
itertools.workspace = true
eyre.workspace = true
